// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	rule "kong-task/cmd/internal/handler/rule"
	"kong-task/cmd/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/v1/rule",
					Handler: rule.CreateRuleHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/v1/rule/:id",
					Handler: rule.UpdateRuleHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/v1/rule",
					Handler: rule.GetRuleHandler(serverCtx),
				},
			}...,
		),
	)
}
